name: 'emSDK Web Build'

on:
  workflow_dispatch:

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        submodules: recursive
    - name: Install emSDK
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest
        ./emsdk activate latest
        cd ..
    - name: download from owncloud
      run: curl -X GET -u ${{ secrets.OWNCLOUD_CREDENTIALS }} "${{ secrets.OWNCLOUD_TARGET }}/precomputed_tss.tar.gz" -o "./precomputed_tss.tar.gz"
    - name: gunzip content
      run: |
        df -h
        ls -larth
        tar -xzvf precomputed_tss.tar.gz precomputed
        ls -larth
        ls -larth precomputed
        ls -larth jsTSS
    - name: Compile web.cpp
      run: |
        source emsdk/emsdk_env.sh
        make web
    - name: gzip content
      run: tar -czvf precompiled_tss.tar.gz precomputed Emscripten/Release web.o
    - name: upload to owncloud
      run: curl -X PUT -u ${{ secrets.OWNCLOUD_CREDENTIALS }} "${{ secrets.OWNCLOUD_TARGET }}/precompiled_tss.tar.gz" --data-binary @"./precompiled_tss.tar.gz"
    - name: store artifact
      if: false
      uses: actions/upload-artifact@v3
      with:
        name: precompiled_tss
        path: |
            precomputed
            Emscripten/Release/jsTSS.html
            web.o
