name: 'emSDK Web Build'

on:
  workflow_dispatch:

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        submodules: recursive
    - name: Install emSDK
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        git pull
        ./emsdk install latest
        ./emsdk activate latest
        cd ..
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        name: precomputed_tss
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: precompute.yml
        path: precomputed
    - name: Compile web.cpp
      run: |
        source emsdk/emsdk_env.sh
        make web
    - name: commit files
      if: false
      run: |
        ls -la
        ls -la precomputed
        git config --local user.email "37019555+danie1kr@users.noreply.github.com"
        git config --local user.name "danie1kr"
        git add precomputed/precomputed_tss_*.o Emscripten/Release/jsTSS.*
        git commit -m "Add compiled web frontend"
    - name: Push changes
      if: false
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
    - uses: geekyeggo/delete-artifact@v2
      with:
          name: precompiled_tss
    - name: store artifact
      uses: actions/upload-artifact@v3
      with:
        name: precompiled_tss
        path: |
            precomputed
            Emscripten/Release/jsTSS.html
            jsTSS/web.o
