name: 'TSS Precompute'

on:
  workflow_dispatch:

jobs:
  precompute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        submodules: recursive
    - name: make solver
      run: make solver
    - name: compute 2
      run: ./timeSaverSolver --cars 2 --outfile precomputed_tss
    - name: compute 3
      run: ./timeSaverSolver --cars 3 --outfile precomputed_tss
    - name: compute 4
      run: ./timeSaverSolver --cars 4 --outfile precomputed_tss
    - name: compute 5
      run: ./timeSaverSolver --cars 5 --outfile precomputed_tss
    - name: commit files
      run: |
        git config --local user.email "37019555+danie1kr@users.noreply.github.com"
        git config --local user.name "danie1kr"
        git add precomputed_tss_*.hpp precomputed_tss_*.cpp
        git commit -m "Add Precomputation Files"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}
