name: 'TSS Precompute'

on:
  workflow_dispatch:

jobs:
  precompute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        submodules: recursive
    - name: make solver
      run: make solver
    - name: compute classic 2
      run: ./timeSaverSolver --cars 2 --outfile precomputed_tss --layout 0
    - name: compute classic 3
      run: ./timeSaverSolver --cars 3 --outfile precomputed_tss --layout 0
    - name: compute classic 4
      run: ./timeSaverSolver --cars 4 --outfile precomputed_tss --layout 0
    - name: compute classic 5
      run: ./timeSaverSolver --cars 5 --outfile precomputed_tss --layout 0
    - name: compute inglenook 2
      run: ./timeSaverSolver --cars 2 --outfile precomputed_tss --layout 1
    - name: compute inglenook 3
      run: ./timeSaverSolver --cars 3 --outfile precomputed_tss --layout 1
    - name: compute inglenook 4
      run: ./timeSaverSolver --cars 4 --outfile precomputed_tss --layout 1
    - name: compute inglenook 5
      run: ./timeSaverSolver --cars 5 --outfile precomputed_tss --layout 1
    - name: commit files
      if: false
      run: |
        git config --local user.email "37019555+danie1kr@users.noreply.github.com"
        git config --local user.name "danie1kr"
        git add precomputed/precomputed_tss_*.hpp precomputed/precomputed_tss_*.cpp
        git commit -m "Add Precomputation Files"
    - name: Push changes
      if: false
      run: |
        #git push origin main:precomputed
        git push origin main
    - name: store artifact
      uses: actions/upload-artifact@v3
      with:
        name: precomputed_tss
        path: precomputed