name: 'TSS Precompute'

on:
  workflow_dispatch:

jobs:
  precompute:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        submodules: recursive
    - name: make solver
      run: make solver
    - name: compute classic 2
      run: ./timeSaverSolver --cars 2 --outfile precomputed_tss --layout 0
    - name: compute classic 3
      run: ./timeSaverSolver --cars 3 --outfile precomputed_tss --layout 0
    - name: compute classic 4
      run: ./timeSaverSolver --cars 4 --outfile precomputed_tss --layout 0
#    - name: compute classic 5
#      run: ./timeSaverSolver --cars 5 --outfile precomputed_tss --layout 0
    - name: compute inglenook 2
      run: ./timeSaverSolver --cars 2 --outfile precomputed_tss --layout 1
    - name: compute inglenook 3
      run: ./timeSaverSolver --cars 3 --outfile precomputed_tss --layout 1
    - name: compute inglenook 4
      run: ./timeSaverSolver --cars 4 --outfile precomputed_tss --layout 1
#    - name: compute inglenook 5
#      run: ./timeSaverSolver --cars 5 --outfile precomputed_tss --layout 1
    - name: gzip content
      run: tar -czvf precomputed_tss.tar.gz precomputed
    - name: upload to owncloud
      run: curl -X PUT -u ${{ secrets.OWNCLOUD_CREDENTIALS }} "${{ secrets.OWNCLOUD_TARGET }}/precomputed_tss.tar.gz" --data-binary @"./precomputed_tss.tar.gz"